### ISSUE TITLE
windows build support

### ISSUE THREAD

**Issue by Luap99** [coreos/stream-metadata-go#38]
PR #18 added https://github.com/google/renameio as dependency however this is [not supported on windows](https://github.com/google/renameio#windows-support)

I wonder is renameio really needed here? Shouldn't be a simple tmpfile + rename be good enough for this use case. In the end this is just a download if the file gets corrupted we can download again.

**Comment by bgilbert** [comment]
Ah yeah, thanks for the report.  Fix in https://github.com/coreos/stream-metadata-go/pull/39.

**Comment by bgilbert** [comment]
#40 adds CI for Windows and macOS.
